#!/usr/bin/python

import pip


def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])


import_or_install('bluepy')
import_or_install('bluepy.btle')
import_or_install('struct')
import_or_install('time')
import_or_install('datetime')

import bluepy.btle
from bluepy.btle import Scanner, DefaultDelegate, ScanEntry, Peripheral
import struct
import time
from datetime import datetime

f = open("mac.txt", "r")
hexiOneAddress = str(f.readline().rstrip())
print(hexiOneAddress)
hexiTwoAddress = str(f.readline().rstrip())
print(hexiTwoAddress)


def try_until_success(func, exception=bluepy.btle.BTLEException, msg='reattempting', args=[]):
    retry = True
    while True:
        try:
            func(*args)
            retry = False
        except exception:
            print msg

        if not retry:
            break


hexiOne = Peripheral()
hexiTwo = Peripheral()

print("Connecting to the first hexiwear")
try_until_success(hexiOne.connect, msg='error connecting to 1',
                  args=[hexiOneAddress])

print("Connecting to the second hexiwear")
try_until_success(hexiTwo.connect, msg='error connecting to 2',
                  args=[hexiTwoAddress])

print("Done connecting")
timeControl = hexiOne.getCharacteristics(uuid='2031')[0]  # Alert Input
timeTwoControl = hexiTwo.getCharacteristics(uuid='2031')[0]  # Alert Input

for i in range(10):
    timeCommand = str(datetime.now().strftime('%H:%M:%S.%f')) + 'aaaaa'
    print(timeCommand)
    try_until_success(timeControl.write, msg='Error sending time to the first one',
                      args=[timeCommand, True])
    try_until_success(timeTwoControl.write, msg='Error sending the time to the second one',
                      args=[timeCommand, True])
    time.sleep(2)
