#!/bin/bash

echo "Installing relevant libraries (if needed)"

echo "Installing paho-mqtt"
sudo pip install paho-mqtt

# import_or_install('paho-mqtt')

echo "Running client program with sudo access (Password might be required)"
sudo python client.py
